language: go
go:
 - "1.x"

os: osx

install: true

env:
  global:
    - CODECOV_TOKEN="936d7a17-608c-4d39-8ce2-2e6d20b93757"

script: go test -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)